package org.sam.game.EvolvedPlayers;

import org.sam.game.GPPlayer;
import org.sam.game.Game;

/**
 * Created by samuel on 10/08/14.
 */
public class SunAug10_14_10_66 extends GPPlayer {

    @Override
    protected long evalGame(char playerColour, char enemyColour, Game game) {
        return (((((((((playerColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        ) : (-4*-1)) >= 0 ? (((enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        ) >= 0 ? (1+-4) : ((enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ) : (0-4)))+(((-5 >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
                : 3))+((playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                >= 0 ? (4 >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        ))))+(((((enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                : -1)+((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        ) >= 0 ? (2 >= 0 ? (playerColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : 1) : (-2 >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
        ) : (0+-2))) >= 0 ? (((-1 >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                : 1)-((playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        )) : ((-4*-2) >= 0 ? ((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                +2))) : ((((playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                +-4) >= 0 ? (0+-4) : ((enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                +4)) >= 0 ? (((playerColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
                -3)+((enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) : ((2-(enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )+(4 >= 0 ? -1 : (enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        ))))) >= 0 ? ((((((playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                +(-3))*(1 >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        ))*(((enemyColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
        )*((playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        ))) >= 0 ? (((3-(enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
        )-(-4 >= 0 ? 3 : -1))-(((enemyColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                >= 0 ? -1 : (enemyColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        ))) : ((((playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                : -2)*((playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
        ))))+(((((enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )+(4*1))-(((playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                >= 0 ? -4 : (playerColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)5, (int)3) ? 1 : 0)
                >= 0 ? 3 : (enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        ))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                : 1)+((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        ))*((-1-(playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                : 1))) : ((((enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
        ) : (-1*(playerColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
        )) >= 0 ? ((4 >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                : 1) >= 0 ? (-3-(enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                : -4))))) : (enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )+(((((((enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )+((playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                : -1)) >= 0 ? (((playerColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                >= 0 ? -3 : (playerColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
        )) : ((-1*(enemyColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
        )*((playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        )))+1) >= 0 ? (((((enemyColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        )+(1+-2)) >= 0 ? ((0+-4) >= 0 ? (0+(enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                >= 0 ? -3 : 0)) : -5)-((((playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        )+(2 >= 0 ? -2 : (playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        )) >= 0 ? (((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                : 2) >= 0 ? (-5*(enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        ) : (0 >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                : 2)) : ((-1 >= 0 ? 2 : 3)*((playerColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )))) : (((((playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                >= 0 ? ((((((enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ))-(((playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                : ((playerColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                >= 0 ? 0 : (playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ))-((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                -(-3)))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )-(0 >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        )) >= 0 ? ((((2-(enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )+(4 >= 0 ? -1 : (enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        ))*0)+(3-(enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                -(-4))+((enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))) : (((4+-1) >= 0 ? ((playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
        ) : (3*-3)) >= 0 ? (((enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) : ((-4-(enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                -2)))) >= 0 ? ((((-3+(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
        ))*(((playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                >= 0 ? -1 : 1)+(-2 >= 0 ? -5 : (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        )))-((((enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                *0)-(3 >= 0 ? 0 : -1)) >= 0 ? ((enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                -(0 >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                : -2)) : ((-2+-4) >= 0 ? (2-(playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                +-3)))) : (((((playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ))*(((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                *3)+((playerColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
        ))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                >= 0 ? -1 : -4)*(2+0))-(((enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ) >= 0 ? (-4 >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                >= 0 ? 1 : (playerColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ))) : ((((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                >= 0 ? -1 : 2)+((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
                *-2) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                >= 0 ? -5 : (playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                +-3))))) : (playerColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                : -2)*((enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
                -(-3))))+((((enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                *-4)*(3 >= 0 ? 4 : -5)) >= 0 ? ((2 >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        )+((playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                *-1)) : (enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )))*(((((((((playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                : -2)*((playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
        ))) >= 0 ? (playerColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
                +-5))*(((enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                >= 0 ? -2 : (playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
        )*(1 >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        )))+((((enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
                -2)+(1 >= 0 ? (playerColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                : 2)-((enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                >= 0 ? -4 : -2)-(-3 >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))))-((((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                *((-4)-(-3)))+((-5*(playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        )+(1+(playerColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
        )))-((((enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                : -5)+((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                : 3)) >= 0 ? (((enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                *-4) >= 0 ? ((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        )) : ((1-(enemyColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        )+((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        )))))))-((((((((playerColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)5, (int)3) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                *-2)) : (((playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                >= 0 ? 0 : 1)+((enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        ))) >= 0 ? ((((playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                *-5) >= 0 ? ((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                *-4) : (0-(enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        ))+(((playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)5, (int)3) ? 1 : 0)
                : 4) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                : -1) : (-4 >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        ))) : ((((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        )) >= 0 ? ((0 >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
        )))) >= 0 ? (((playerColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        )) : (((((playerColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
        )+(-4-(playerColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
        ))*(((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
        )))-((((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        ))-(((enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        )+(-2 >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
        ))))) >= 0 ? ((((((enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ))-(((playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                : ((playerColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                >= 0 ? 0 : (playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ))-((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                -(-3)))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )-(0 >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        )) >= 0 ? ((((2-(enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
        )+(4 >= 0 ? -1 : (enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        ))*0)+(3-(enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                -(-4))+((enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))) : (((4+-1) >= 0 ? ((playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
        ) : (3*-3)) >= 0 ? (((enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) : ((-4-(enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ) >= 0 ? ((playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                -2)))) >= 0 ? ((((-3+(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
        ))*(((playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                >= 0 ? -1 : 1)+(-2 >= 0 ? -5 : (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        )))-((((enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                *0)-(3 >= 0 ? 0 : -1)) >= 0 ? ((enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                -(0 >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                : -2)) : ((-2+ -4) >= 0 ? (2-(playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                +-3)))) : (((((playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ))*(((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                *3)+((playerColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
        ))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                >= 0 ? -1 : -4)*(2+0))-(((enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ) >= 0 ? (-4 >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                >= 0 ? 1 : (playerColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ))) : ((((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                >= 0 ? -1 : 2)+((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
                *-2) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                >= 0 ? -5 : (playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                +-3))))) : (((((-3-2)*((enemyColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                >= 0 ? -1 : -2))+((1 >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        ) >= 0 ? (1*(playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        ) : (0 >= 0 ? (enemyColour == game.getColourOfStone((int)5, (int)3) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
        )))-((((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
        )*((playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        )) >= 0 ? ((playerColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                >= 0 ? ((playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
                >= 0 ? 4 : (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) : (((enemyColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                -1))))+(((((playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                -1)-((enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                - -1))*(((playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                : 1)*((enemyColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                +-1)))-((((enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                >= 0 ? 1 : (playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
        )*(-2+ -5))+((0* -2)+((playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
                >= 0 ? -1 : (playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        ))))))-((((((-5*(playerColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
        ) >= 0 ? (-1 >= 0 ? -2 : (playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
                - -1))*(((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                *-3) : ((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )))+((((enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
        )*(1+1)) >= 0 ? (0*((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                : 4)) : (((playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)6, (int)2) ? 1 : 0)
                *((enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        ))+(((enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
                +-1)*(-5-4))) >= 0 ? ((((enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) >= 0 ? ((2*(enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
        )+((playerColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
        ) : (1+(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        ))) : (((0+ -4) >= 0 ? ( 0 + (enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                >= 0 ? -3 : 0)) >= 0 ? (((playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
        )) : ((0 + (playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
        ) >= 0 ? (0-(enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)4, (int)4) ? 1 : 0)
                *-1)))) : ((((-4+(enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        )+((enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
        ))-(((playerColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
                : 3) >= 0 ? (4 >= 0 ? (enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                *-5))) >= 0 ? (((-1*-2)*(-5 >= 0 ? -1 : (playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )-(-3+(enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
        )*(-4 >= 0 ? 1 : (playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        ))) : ((((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                >= 0 ? -3 : (enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        ) : (-2 >= 0 ? -2 : (playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
        ))*(((enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
                : 3) >= 0 ? ((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        ))))) >= 0 ? ((((((enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        )) >= 0 ? (((enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                +2) >= 0 ? ((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                >= 0 ? 2 : -2) : ((playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)0) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
        )) : ((2-0)*((playerColour == game.getColourOfStone((int)6, (int)0) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                : -5)))-(((-4*(playerColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        ))-(((playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                - -3) >= 0 ? (-1-(enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        ) : (-1-(enemyColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        )))) >= 0 ? (((((playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
        ) >= 0 ? (-4 >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
        ) : (2*(enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        ))-(((enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                +-4) : ((playerColour == game.getColourOfStone((int)4, (int)3) ? 1 : 0)
                *-4)))*((((enemyColour == game.getColourOfStone((int)5, (int)0) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
        )-(-4-(enemyColour == game.getColourOfStone((int)6, (int)3) ? 1 : 0)
        ))-(((enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
        )+(4+(playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        )))) : (((((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                *-3)+(-5*(playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)5, (int)5) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                -2)-((playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        )))+((((playerColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                >= 0 ? 2 : (playerColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
                +-5))*((-5 >= 0 ? 1 : (enemyColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)1, (int)2) ? 1 : 0)
                >= 0 ? -4 : (enemyColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
        ))))) : ((((((enemyColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                +-1) >= 0 ? ((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)5, (int)1) ? 1 : 0)
        ) : (3+2)) >= 0 ? (((playerColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
        )*((enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                *(playerColour == game.getColourOfStone((int)1, (int)3) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                >= 0 ? ((1*4)+((playerColour == game.getColourOfStone((int)4, (int)0) ? 1 : 0)
                >= 0 ? 0 : (playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        )) : -3)+((playerColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)2, (int)0) ? 1 : 0)
        ))) >= 0 ? ((((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                +0)*((enemyColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
        ))*((-4 >= 0 ? (playerColour == game.getColourOfStone((int)4, (int)1) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)1) ? 1 : 0)
        )-((playerColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)3, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        ))) : (((-5*2) >= 0 ? (-5*(playerColour == game.getColourOfStone((int)0, (int)3) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                -(enemyColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
        )) >= 0 ? (((playerColour == game.getColourOfStone((int)0, (int)4) ? 1 : 0)
                -4)-((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)1) ? 1 : 0)
        )) : (((playerColour == game.getColourOfStone((int)1, (int)0) ? 1 : 0)
                -(playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
                *0) : (0+(enemyColour == game.getColourOfStone((int)5, (int)4) ? 1 : 0)
        ))))-(((((enemyColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)4, (int)5) ? 1 : 0)
        )*0) >= 0 ? (((playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                *(enemyColour == game.getColourOfStone((int)4, (int)2) ? 1 : 0)
        ) >= 0 ? ((enemyColour == game.getColourOfStone((int)1, (int)1) ? 1 : 0)
                >= 0 ? (enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
        ) : ((enemyColour == game.getColourOfStone((int)1, (int)4) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)2, (int)4) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)2, (int)5) ? 1 : 0)
        )) : ((-2 >= 0 ? 3 : (enemyColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
        )+(4 >= 0 ? (enemyColour == game.getColourOfStone((int)0, (int)5) ? 1 : 0)
                : 3))) >= 0 ? (((-3*(enemyColour == game.getColourOfStone((int)0, (int)2) ? 1 : 0)
        )-((enemyColour == game.getColourOfStone((int)6, (int)4) ? 1 : 0)
                +-2)) >= 0 ? (((playerColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                +(enemyColour == game.getColourOfStone((int)2, (int)2) ? 1 : 0)
        )*((playerColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
                +(playerColour == game.getColourOfStone((int)3, (int)2) ? 1 : 0)
        )) : (((enemyColour == game.getColourOfStone((int)6, (int)5) ? 1 : 0)
                >= 0 ? 1 : (enemyColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        )+(0 >= 0 ? (playerColour == game.getColourOfStone((int)1, (int)5) ? 1 : 0)
                : (playerColour == game.getColourOfStone((int)3, (int)4) ? 1 : 0)
        ))) : ((((playerColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
                >= 0 ? (playerColour == game.getColourOfStone((int)3, (int)3) ? 1 : 0)
                : (enemyColour == game.getColourOfStone((int)2, (int)3) ? 1 : 0)
        ) >= 0 ? (3 >= 0 ? -5 : (enemyColour == game.getColourOfStone((int)0, (int)0) ? 1 : 0)
        ) : ((playerColour == game.getColourOfStone((int)6, (int)1) ? 1 : 0)
                *1))-((0*(playerColour == game.getColourOfStone((int)3, (int)1) ? 1 : 0)
        )+((playerColour == game.getColourOfStone((int)5, (int)2) ? 1 : 0)
                *0))))))));
    }
}
